name: delopyment (still under Development)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: display development message
        run: echo "  project still under development"
