name: to run tests when pushing the code

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # best option (fast and free)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # we can use 3.12 if needed as well

      - name: install Dependencies needed 
        run: |
          pip install -r requirements.txt 

      - name: Run Tests
        run: |
          pytest
